spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/userdb?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: password

gateway:
  ip: 172.30.1.33

sampler-common-property: "this is common property"
